apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-microservice-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: new-microservice-deployment
  template:
    metadata:
      labels:
        app: new-microservice-deployment
    spec:
      containers:
      - name: new-microservice-deployment
        image: new-microservice-deployment:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: new-microservice-deployment
spec:
  type: NodePort
  selector:
    app: new-microservice-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
